"""Add nullable-True for a created_at model Order

Revision ID: 13735dba61ea
Revises: d84905f5bc30
Create Date: 2024-10-10 14:32:59.537817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13735dba61ea'
down_revision: Union[str, None] = 'd84905f5bc30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
