"""Add cascade delete to models

Revision ID: 5d128d061ed6
Revises: beb9df654e8e
Create Date: 2024-10-13 14:12:41.304335

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5d128d061ed6"
down_revision: Union[str, None] = "beb9df654e8e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("order_items_product_id_fkey", "order_items", type_="foreignkey")
    op.drop_constraint("order_items_order_id_fkey", "order_items", type_="foreignkey")
    op.create_foreign_key(
        None, "order_items", "orders", ["order_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None, "order_items", "products", ["product_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "order_items", type_="foreignkey")
    op.drop_constraint(None, "order_items", type_="foreignkey")
    op.create_foreign_key(
        "order_items_order_id_fkey", "order_items", "orders", ["order_id"], ["id"]
    )
    op.create_foreign_key(
        "order_items_product_id_fkey", "order_items", "products", ["product_id"], ["id"]
    )
    # ### end Alembic commands ###
