"""Add nullable to created_at field in orders table

Revision ID: 64342b1b6d67
Revises: b7475b8ea1ea
Create Date: 2024-10-10 14:17:43.764678

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "64342b1b6d67"
down_revision: Union[str, None] = "b7475b8ea1ea"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
